blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name


urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activite/<int:pk>', toggle_activity, name='toggle'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='заголовок')
    slug = models.CharField(max_length=50, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение')
    date_of_creation = models.DateTimeField(verbose_name='дата создания')
    sign_of_publication = models.BooleanField(default=True, verbose_name='признак публикации')
    count_views = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'

blog/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


# Create your views here.

class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'date_of_creation',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(sign_of_publication=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'date_of_creation',)

    def get_success_url(self):
        return reverse('blog:view', args=[self.object.pk])

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


def toggle_activity(request, pk):
    blog_data = get_object_or_404(Blog, pk=pk)
    if blog_data.sign_of_publication:
        blog_data.sign_of_publication = False
    else:
        blog_data.sign_of_publication = True

    blog_data.save()

    return redirect(reverse('blog:list'))


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/includes/base.html' %}

{% block context %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body centered">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить материал "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'blog:list' %}" class="btn btn-warning ">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/includes/base.html' %}
{% load my_tags %}
{% block context %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Информация
                        </h3>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Заголовок</td>
                                <td>{{ object.title }} ({{ object.slug }})</td>
                            </tr>
                            <tr>
                                <td>Содержимое</td>
                                <td>{{ object.content }}</td>
                            </tr>
                            <tr>
                                <td>Дата создания</td>
                                <td>{{ object.date_of_creation }}</td>
                            </tr>
                            <tr class="card-footer">
                                <td>Просмотры:</td>
                                <td>{{ object.count_views }}</td>
                            </tr>
                        </table>
                    </div>
                     <div class="btn-group">
                         <a href="{% url 'blog:update' object.pk %}" class="btn btn-primary active" aria-current="page">Редактировать</a>
                         <a href="{% url 'blog:delete' object.pk %}" class="btn btn-danger">Удалить</a>
                     </div>
                </div>
            </div>
            <div class="col-6">
                <img class="card-img-top" src="{{ object.preview|mediapath }}"
                    alt=""/>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/includes/base.html' %}

{% block context %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body col-3">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Изменить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/includes/base.html' %}
{% load my_tags %}

{% block context %}
    <div class="col-12 mb-5">
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:create' %}">Добавить материал</a>
    </div>
        {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Информация</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ object.title }}</h1>
                        <h3 class="card-text">{{ object.content|stringformat:".12s" }}</h3>
                        <img class="card-img-top" src="{{ object.preview|mediapath }}"
                        alt=""/>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        </ul>
                        <div class="col-12 mb-5">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:view' object.pk %}">Просмотр</a>
                        </div>
                        {% if object.sign_of_publication %}
                            <a class="btn btn-warning" href="{% url 'blog:toggle' object.pk %}">Деактивировать</a>
                        {% else %}
                            <a class="btn btn-success" href="{% url 'blog:toggle' object.pk %}">Активировать</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
{% endblock %}