blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name


urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activite/<int:pk>', toggle_activity, name='toggle'),
]

catalog/urls.py
from django.urls import path

from catalog.views import HomeListView, CategoryListView, ProductListView,\
    ProductCreateView, ProductUpdateView, ProductDeleteView, ProductDetailView


urlpatterns = [
    path('', HomeListView.as_view(), name='product'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('product/<int:pk>/', ProductListView.as_view(), name='categories_product'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('view/<int:pk>/', (ProductDetailView.as_view()), name='view_product'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, VerifyEmailView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('email-confirmation/', TemplateView.as_view(template_name='users/email_confirmation_sent.html'),
         name='email_confirmation'),
    path('verify/<int:rnd_key>/', VerifyEmailView.as_view(), name='verify_email'),
    path('email-confirmed/', TemplateView.as_view(template_name='users/email_confirmed.html'), name='email_confirmed'),
    path('email-confirmation-failed/', TemplateView.as_view(template_name='users/email_confirmation_failed.html'),
         name='email_confirmation_failed'),
]

catalog/models.py
from django.conf import settings
from django.db import models

# Create your models here.
NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.CharField(max_length=150, verbose_name='Описание')
    image = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория товара')
    price = models.IntegerField(verbose_name='Цена за покупку')
    date_create = models.DateTimeField(**NULLABLE, verbose_name='Дата создания')
    date_last_fix = models.DateTimeField(**NULLABLE, verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='Публикация товара')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              **NULLABLE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.name}\n Категория: {self.category} \nЦена: {self.price}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        permissions = [
            ('set_published', 'Can publish posts'),
            ('change_prod_description', 'change product description'),
            ('change_category_id', 'change category')
        ]


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Категория')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='product_ver')
    number_vers = models.IntegerField(verbose_name='номер версии')
    name_vers = models.CharField(max_length=50, verbose_name='название версии')
    last_vers = models.BooleanField(default=True, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.name_vers}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from django.forms import BaseInlineFormSet

from catalog.models import Product, Category, Version

STOP_LIST = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('owner',)

    def clean_name(self):
        name = self.cleaned_data.get('name')

        for word in STOP_LIST:
            if word in name:
                raise forms.ValidationError('Использование запрещенного слова')

            return name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if field_name == 'is_published':
                field.widget.attrs['class'] = 'form-chek-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class CategoryForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'
        include = 'product'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if field_name == 'last_vers':
                field.widget.attrs['class'] = 'form-chek-input'
            else:
                field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from catalog.forms import ProductForm, CategoryForm, VersionForm
from catalog.models import Product, Category, Version
from catalog.services import get_cached_subjects_for_product, get_cached_subjects_for_categories


class CategoryListView(ListView):
    model = Category
    form_class = CategoryForm
    template_name = 'catalog/category_list.html'
    get_cached_subjects_for_categories()


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'

    def get_success_url(self):
        return reverse('view_product', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = ['catalog.set_published',
                           'catalog.change_prod_description',
                           'catalog.change_category_id',
                           'catalog.change_product'
                           ]

    def get_success_url(self):
        return reverse('view_product', args=[self.object.pk])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class HomeListView(ListView):
    model = Product
    template_name = 'catalog/home_list.html'


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home_list.html'
    permission_required = 'catalog.view_product'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(category_id=self.kwargs.get('pk'))
        queryset = queryset.filter(
            category_id=self.kwargs.get('pk')
        )
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk,
        context_data['title'] = f'Продукты, категории {category_item.name}'

        return context_data


class ProductDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    permission_required = 'catalog.view_product'

    def get_context_data(self, subject_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['subjects'] = get_cached_subjects_for_product()
        return context_data


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    permission_required = 'catalog.delete_product'

    def get_success_url(self):
        return reverse('product')

catalog/templates/catalog/includes/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    {% include 'catalog/includes/inc_base.html' %}
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        {% block context %}
        {% endblock %}
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/includes/home_list.html
{% extends 'catalog/includes/base.html' %}
{% load my_tags %}
{% block context %}
{% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Продуктовый отдел</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.name|title }}</h1>
                    <h3 class="card-text">{{ object.category }}</h3>
                    <h2 class="card-text">Цена: {{ object.price }}</h2>
                    <img class="card-img-top" src="{{ object.image|mediapath }}"
                    alt=""/>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">В корзину</button>
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock %}

catalog/templates/catalog/includes/inc_base.html
<h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <div class="row">
            <div class="col-11 mb-3">
                <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Материалы</a>
                <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'categories' %}">Категории</a>
            </div>
            <div class="col-6">
                 {% if user.is_authenticated %}
                    <a class="p-2 btn btn-primary align-right" href="{% url 'users:profile' %}">Профиль</a>
                    <a class="p-2 btn btn-primary align-right" href="{% url 'users:logout' %}">Выход</a>
                 {% else %}
                    <a class="p-2 btn btn-primary" href="{% url 'users:login' %}">Войти</a>
                    <a class="p-2 btn btn-primary" href="{% url 'users:register' %}">Регистрация</a>
                 {% endif %}
            </div>
        </div>
    </nav>