blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name


urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activite/<int:pk>', toggle_activity, name='toggle'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, VerifyEmailView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('email-confirmation/', TemplateView.as_view(template_name='users/email_confirmation_sent.html'),
         name='email_confirmation'),
    path('verify/<int:rnd_key>/', VerifyEmailView.as_view(), name='verify_email'),
    path('email-confirmed/', TemplateView.as_view(template_name='users/email_confirmed.html'), name='email_confirmed'),
    path('email-confirmation-failed/', TemplateView.as_view(template_name='users/email_confirmation_failed.html'),
         name='email_confirmation_failed'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(verbose_name='почта', unique=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)
    country = models.TextField(verbose_name='страна')

    is_active = models.BooleanField(default=False)
    rnd_key = models.IntegerField(default=0, verbose_name='ключ для верификации')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from catalog.forms import StyleFormMixin
from users.models import User


class UserRegistrForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'avatar', 'phone', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from random import randint

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView
from config import settings
from users.forms import UserRegistrForm, UserForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegistrForm
    success_url = reverse_lazy('users:email_confirmation')

    def form_valid(self, form):
        user = form.save()
        user.rnd_key = randint(1, 2147483644)
        user.save()
        verify_url = reverse('users:verify_email', args=[user.rnd_key])
        verify_link = self.request.build_absolute_uri(verify_url)
        send_mail(
            subject='Подтвердите свой электронный адрес',
            message=f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: {verify_link}',
            from_email='Unfearble@yandex.ru',
            recipient_list=[user.email, ],
            fail_silently=False
        )
        return super().form_valid(form)


class VerifyEmailView(View):
    def get(self, request, rnd_key):
        try:
            user = User.objects.get(rnd_key=rnd_key)
            user.is_active = True
            user.save()
            return HttpResponseRedirect(reverse('users:email_confirmed'))
        except User.DoesNotExist:
            return HttpResponseRedirect(reverse('users:email_confirmation_failed'))


class EmailConfirmationView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'


class EmailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def generate_new_password(request):
    new_password = ''.join([str(randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('product'))

users/templates/users/email_confirmation_failed.html
{% extends 'catalog/includes/base.html' %}
{% block context %}
    <div class="container">
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="alert alert-danger">
                <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
                <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек. Пожалуйста, зарегистрируйтесь снова.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends 'catalog/includes/base.html' %}
{% block context %}
    <div class="container">
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="alert alert-secondary">
                <h3 class="alert-heading">Подтвердите свой адрес электронной почты</h3>
                <p>Пожалуйста, проверьте вашу почту и подтвердите адрес электронной почты.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/email_confirmed.html
{% extends 'catalog/includes/base.html' %}
{% block context %}
    <div class="container">
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="alert alert-success">
                <h3 class="alert-heading">Почта успешно подтверждена</h3>
                <p>Ваш адрес электронной почты был успешно подтвержден.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/includes/base.html' %}
{% block context %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Вход</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/includes/base.html' %}
{% block context %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/includes/base.html' %}
{% block context %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить профиль</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:generate_new_password' %}" class="btn btn-outline-danger">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
    </div>
{% endblock %}